version: "3"
services:
  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ALLOW_ORIGIN: "*"
      CORS_ALLOW_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      CORS_ALLOW_HEADERS: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "128.52.139.178:3000"